name: Deploy Manual (custom config)

on:
  workflow_dispatch:
    inputs:
      SITE_URL:
        description: 'URL completa del sitio (ej: https://blog.fershouno.me)'
        required: true
        default: 'https://fershunoo.github.io/blog'
      CNAME:
        description: 'Dominio personalizado (opcional, ej: blog.fershouno.me)'
        required: false
        default: ''

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      - run: npm run build
        env:
          SITE_URL: ${{ github.event.inputs.SITE_URL }}
          SITE_NAME: Debian MicroNews
          SITE_DESC: Noticias sobre Debian, GNU/Linux y Software Libre
          CNAME: ${{ github.event.inputs.CNAME }}

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4
